### ISSUE TITLE
Start command

### ISSUE THREAD

**Issue by dimitrovs** [alibhojani/comp535Project#3]
**start**: start this router and initialize the database synchronization process.

After you run start message, the router where this command is triggered should send HELLO
messages to all routers which have been linked via attach command.
The process of handling HELLO is as following:  
a. Router 1 (R1) broadcast HELLO messages through all ports  
b. the remote end (R2) receives a HELLO message, set the status in the RouterDescription  
of R1 as INIT, then sends HELLO to R1 
c. R1 receives the HELLO from R2, set the status of R1 as TWO_WAY, sends HELLO to R2  
d. R2 receives HELLO from R1, set status of R1 as TWO_WAY

**Comment by dimitrovs** [comment]
It's not done yet.

**Comment by alibhojani** [comment]
oh whoops, i thought this was all in the the sync issue. I found the relevant part of the PDF where it says exactly when LSUpdates are required. You actually copy pasted it in the sync issue :)
